spring:
  application:
    name: eventhub
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://demo-keyvault-patri.vault.azure.net
          tenant-id: ${AZURE_TENANT_ID}
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
      eventhubs:
        producer-0:
          connection-string-secret-name: demo-event-hub-patri-producer-0-connectionstring
        consumer-0:
          connection-string-secret-name: demo-event-hub-patri-consumer-0-connectionstring
          consumer-group: $Default
        processor:
          checkpoint-store:
            connection-string-secret-name: demo-event-hub-patri-checkpoint-store-connectionstring
            container-name: demo-eventhub-checkpoint

server:
  port: 8080
  servlet:
    context-path: /eventhub

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@