spring:
  application:
    name: eventhub

server:
  port: 8080
  servlet:
    context-path: /eventhub

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@