spring:
  application:
    name: eventhub
  stream:
    bindings:
      consume-in-0:
        connection-string: Endpoint=sb://demo-eventhub-patri.servicebus.windows.net/;SharedAccessKeyName=consumer;SharedAccessKey=;EntityPath=demo-01
        consumer-group: consumer-group-1
      supply-out-0:
        connection-string: Endpoint=sb://demo-eventhub-patri.servicebus.windows.net/;SharedAccessKeyName=producer;SharedAccessKey=;EntityPath=demo-01

server:
  port: 8080
  servlet:
    context-path: /eventhub

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@